GAME_FPS = 0
MAIN = 0

DATAS_FOLDER_NAME = 'assets'

NAME_PRINT_PROCESS = 'Print Sketch {num}'

HORZRES = 8
VERTRES = 10
LOGPIXELSX = 88
LOGPIXELSY = 90
PHYSICALWIDTH = 110
PHYSICALHEIGHT = 111
PHYSICALOFFSETX = 112
PHYSICALOFFSETY = 113
